/**
 * Generated Supabase database types (schema: public).
 *
 * Generated by: pnpm db:types
 *   (supabase gen types typescript --local --schema public | prettier --parser=typescript)
 *
 * Status: M0-P3 produced this with @supabase/postgres-meta 0.99.0 (the generator behind the CLI)
 * against a local Postgres 16 with all migrations applied, because the sandbox has no Docker.
 * The CI `db` job regenerates it with the real CLI and fails on drift; if it reports a diff,
 * take the file from branch bot/db-types.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      institutions: {
        Row: {
          created_at: string;
          created_by: string | null;
          id: string;
          name_bn: string | null;
          name_en: string | null;
          slug: string;
          status: string;
          type: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name_bn?: string | null;
          name_en?: string | null;
          slug: string;
          status?: string;
          type?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name_bn?: string | null;
          name_en?: string | null;
          slug?: string;
          status?: string;
          type?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          created_at: string;
          created_by: string | null;
          id: string;
          institution_id: string;
          invited_by: string | null;
          profile_id: string;
          role: string;
          status: string;
          updated_at: string;
          updated_by: string | null;
          username: string | null;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          institution_id: string;
          invited_by?: string | null;
          profile_id: string;
          role: string;
          status?: string;
          updated_at?: string;
          updated_by?: string | null;
          username?: string | null;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          institution_id?: string;
          invited_by?: string | null;
          profile_id?: string;
          role?: string;
          status?: string;
          updated_at?: string;
          updated_by?: string | null;
          username?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "memberships_institution_id_fkey";
            columns: ["institution_id"];
            isOneToOne: false;
            referencedRelation: "institutions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "memberships_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "memberships_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          created_by: string | null;
          full_name: string;
          id: string;
          locale: string;
          must_change_password: boolean;
          phone_e164: string | null;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          full_name: string;
          id: string;
          locale?: string;
          must_change_password?: boolean;
          phone_e164?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          full_name?: string;
          id?: string;
          locale?: string;
          must_change_password?: boolean;
          phone_e164?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      pg_all_foreign_keys: {
        Row: {
          fk_columns: unknown[] | null;
          fk_constraint_name: unknown;
          fk_schema_name: unknown;
          fk_table_name: unknown;
          fk_table_oid: unknown;
          is_deferrable: boolean | null;
          is_deferred: boolean | null;
          match_type: string | null;
          on_delete: string | null;
          on_update: string | null;
          pk_columns: unknown[] | null;
          pk_constraint_name: unknown;
          pk_index_name: unknown;
          pk_schema_name: unknown;
          pk_table_name: unknown;
          pk_table_oid: unknown;
        };
        Relationships: [];
      };
      tap_funky: {
        Row: {
          args: string | null;
          is_definer: boolean | null;
          is_strict: boolean | null;
          is_visible: boolean | null;
          kind: unknown;
          langoid: unknown;
          name: unknown;
          oid: unknown;
          owner: unknown;
          returns: string | null;
          returns_set: boolean | null;
          schema: unknown;
          volatility: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      _cleanup: { Args: Record<PropertyKey, never>; Returns: boolean };
      _contract_on: { Args: { "": string }; Returns: unknown };
      _currtest: { Args: Record<PropertyKey, never>; Returns: number };
      _db_privs: { Args: Record<PropertyKey, never>; Returns: unknown[] };
      _extensions: { Args: Record<PropertyKey, never>; Returns: unknown[] };
      _get: { Args: { "": string }; Returns: number };
      _get_latest: { Args: { "": string }; Returns: number[] };
      _get_note: { Args: { "": string }; Returns: string };
      _is_verbose: { Args: Record<PropertyKey, never>; Returns: boolean };
      _prokind: { Args: { p_oid: unknown }; Returns: unknown };
      _query: { Args: { "": string }; Returns: string };
      _refine_vol: { Args: { "": string }; Returns: string };
      _retval: { Args: { "": string }; Returns: string };
      _table_privs: { Args: Record<PropertyKey, never>; Returns: unknown[] };
      _temptypes: { Args: { "": string }; Returns: string };
      _todo: { Args: Record<PropertyKey, never>; Returns: string };
      col_is_null:
        | {
            Args: {
              column_name: unknown;
              description?: string;
              schema_name: unknown;
              table_name: unknown;
            };
            Returns: string;
          }
        | {
            Args: {
              column_name: unknown;
              description?: string;
              table_name: unknown;
            };
            Returns: string;
          };
      col_not_null:
        | {
            Args: {
              column_name: unknown;
              description?: string;
              schema_name: unknown;
              table_name: unknown;
            };
            Returns: string;
          }
        | {
            Args: {
              column_name: unknown;
              description?: string;
              table_name: unknown;
            };
            Returns: string;
          };
      dearmor: { Args: { "": string }; Returns: string };
      diag:
        | {
            Args: { msg: unknown };
            Returns: {
              error: true;
            } & "Could not choose the best candidate function between: public.diag(msg => text), public.diag(msg => anyelement). Try renaming the parameters or the function itself in the database so function overloading can be resolved";
          }
        | {
            Args: { msg: string };
            Returns: {
              error: true;
            } & "Could not choose the best candidate function between: public.diag(msg => text), public.diag(msg => anyelement). Try renaming the parameters or the function itself in the database so function overloading can be resolved";
          };
      diag_test_name: { Args: { "": string }; Returns: string };
      do_tap:
        | { Args: Record<PropertyKey, never>; Returns: string[] }
        | { Args: { "": string }; Returns: string[] };
      fail:
        | { Args: Record<PropertyKey, never>; Returns: string }
        | { Args: { "": string }; Returns: string };
      findfuncs: { Args: { "": string }; Returns: string[] };
      finish: { Args: { exception_on_failure?: boolean }; Returns: string[] };
      format_type_string: { Args: { "": string }; Returns: string };
      gen_random_uuid: { Args: Record<PropertyKey, never>; Returns: string };
      gen_salt: { Args: { "": string }; Returns: string };
      has_unique: { Args: { "": string }; Returns: string };
      in_todo: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_empty: { Args: { "": string }; Returns: string };
      isnt_empty: { Args: { "": string }; Returns: string };
      lives_ok: { Args: { "": string }; Returns: string };
      no_plan: { Args: Record<PropertyKey, never>; Returns: boolean[] };
      num_failed: { Args: Record<PropertyKey, never>; Returns: number };
      os_name: { Args: Record<PropertyKey, never>; Returns: string };
      pass:
        | { Args: Record<PropertyKey, never>; Returns: string }
        | { Args: { "": string }; Returns: string };
      pg_version: { Args: Record<PropertyKey, never>; Returns: string };
      pg_version_num: { Args: Record<PropertyKey, never>; Returns: number };
      pgp_armor_headers: {
        Args: { "": string };
        Returns: Record<string, unknown>[];
      };
      pgtap_version: { Args: Record<PropertyKey, never>; Returns: number };
      runtests:
        | { Args: Record<PropertyKey, never>; Returns: string[] }
        | { Args: { "": string }; Returns: string[] };
      skip:
        | { Args: { "": string }; Returns: string }
        | { Args: { how_many: number; why: string }; Returns: string };
      throws_ok: { Args: { "": string }; Returns: string };
      todo:
        | { Args: { how_many: number }; Returns: boolean[] }
        | { Args: { how_many: number; why: string }; Returns: boolean[] }
        | { Args: { why: string }; Returns: boolean[] }
        | { Args: { how_many: number; why: string }; Returns: boolean[] };
      todo_end: { Args: Record<PropertyKey, never>; Returns: boolean[] };
      todo_start:
        | { Args: Record<PropertyKey, never>; Returns: boolean[] }
        | { Args: { "": string }; Returns: boolean[] };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      _time_trial_type: {
        a_time: number | null;
      };
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
