/**
 * Generated Supabase database types (schema: public).
 *
 * Generated by (or matching the shape produced by):
 *   pnpm db:types
 *   # i.e. supabase gen types typescript --local --schema public > packages/db/src/types.ts
 *
 * DO NOT HAND-EDIT past this point once real product tables exist — regenerate
 * instead, and let the CI `db` job (docs/tasks/M0-P2.md step 6) fail the build
 * if a regenerated file would differ from what's committed here (schema/type
 * drift). This exact file was hand-authored to match the *current* schema
 * state (the baseline migration adds only a `private` schema with two helper
 * functions, and `private` is not in config.toml's exposed API schemas, so
 * `public` has zero tables/views/functions right now) — it was not produced
 * by actually running the command, because this environment has no Docker
 * and cannot start a local Supabase instance. See docs/reports/M0-P2.md
 * "Deviations" for how to regenerate and confirm this for real.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
