/**
 * Generated Supabase database types (schema: public).
 *
 * Generated by:
 *   pnpm db:types
 *   # i.e. supabase gen types typescript --local --schema public | prettier --parser=typescript > packages/db/src/types.ts
 *
 * DO NOT HAND-EDIT past this point once real product tables exist — regenerate
 * instead, and let the CI `db` job (docs/tasks/M0-P2.md step 6) fail the build
 * if a regenerated file would differ from what's committed here (schema/type
 * drift).
 *
 * Status of this exact file: this content is a best-effort match for Supabase
 * CLI 2.117.0's actual output for a schema with zero public tables — it was
 * NOT produced by actually running the command, because this sandbox has no
 * Docker and cannot start a local Supabase instance (see
 * docs/reports/M0-P2.md "Deviations"). A real CI run of the `db` job's
 * "Regenerate types and fail on drift" step did in fact catch this file as
 * out of date on the first attempt — proving the drift check works — and the
 * Owner needs to run `pnpm db:types` once on a machine with Docker (or let a
 * CI run generate it) and commit the real output to close this out for good.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: string;
  };
  public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
