// Generates src/styles/tokens.css one to one from docs/spec/design-tokens.json.
// Usage: node scripts/generate-tokens.mjs [--check]   (--check fails when the file is stale)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tokensPath = resolve(here, "../../../docs/spec/design-tokens.json");
const outPath = resolve(here, "../src/styles/tokens.css");

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** Flattens { surface: { base: "#fff" } } into [["surface-base", "#fff"]]. */
function flat(obj, prefix = []) {
  return Object.entries(obj).flatMap(([k, v]) =>
    typeof v === "object" && v !== null ? flat(v, [...prefix, kebab(k)]) : [[[...prefix, kebab(k)].join("-"), v]],
  );
}

const decl = (pairs, indent) => pairs.map(([name, value]) => `${indent}${name}: ${value};`).join("\n");

export function renderTokensCss(tokens) {
  const colorVars = (theme) => flat(tokens.color[theme]).map(([n, v]) => [`--color-${n}`, v]);
  const shadowVars = (theme) => flat(tokens.elevation[theme]).map(([n, v]) => [`--shadow-${n}`, v]);

  const shared = [
    ["--font-bangla", '"Hind Siliguri", "Noto Sans Bengali", -apple-system, "Segoe UI", Roboto, sans-serif'],
    ...Object.entries(tokens.typeScale)
      .filter(([, v]) => typeof v === "object")
      .flatMap(([k, v]) => [
        [`--text-${kebab(k)}`, v.size],
        [`--text-${kebab(k)}-leading`, String(v.lineHeight)],
      ]),
    ...Object.entries(tokens.spacing).map(([k, v]) => [`--space-${k}`, v]),
    ...Object.entries(tokens.radius).map(([k, v]) => [`--radius-${k}`, v]),
    ...Object.entries(tokens.motion.duration).map(([k, v]) => [`--duration-${k}`, v]),
    ...Object.entries(tokens.motion.easing).map(([k, v]) => [`--ease-${k}`, v]),
    ...Object.entries(tokens.zIndex).map(([k, v]) => [`--z-${kebab(k)}`, String(v)]),
    ...Object.entries(tokens.breakpoints).map(([k, v]) => [`--breakpoint-${k}`, v]),
  ];

  const light = [...colorVars("light"), ...shadowVars("light")];
  const dark = [...colorVars("dark"), ...shadowVars("dark")];

  return `/* GENERATED by packages/ui/scripts/generate-tokens.mjs from docs/spec/design-tokens.json. Do not edit. */

:root {
${decl(shared, "  ")}
  color-scheme: light;
${decl(light, "  ")}
}

:root[data-theme="dark"] {
  color-scheme: dark;
${decl(dark, "  ")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${decl(dark, "    ")}
  }
}

/* ${tokens.motion.reducedMotion.rule}: no slide or scale motion; only very short fades remain. */
@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: ${tokens.motion.duration.fast} !important;
    transition-property: opacity !important;
    scroll-behavior: auto !important;
  }
  .motion-essential {
    animation-duration: 1s !important;
    animation-iteration-count: infinite !important;
  }
}
`;
}

const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));
const css = renderTokensCss(tokens);

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(outPath, "utf8");
  } catch {
    /* missing file counts as stale */
  }
  if (current !== css) {
    process.stderr.write("tokens.css is stale. Run: pnpm --filter @sms/ui tokens:generate\n");
    process.exit(1);
  }
  process.stdout.write("tokens.css is up to date\n");
} else {
  writeFileSync(outPath, css);
  process.stdout.write(`wrote ${outPath}\n`);
}
