import Dexie, { type Table } from "dexie";

import type { ApplyOpResult, Entity, OutboxOp, Payload, OutboxStatus } from "./types.js";

/** The client-side outbox database. One row per queued write, keyed by its own op_id. */
export class OutboxDatabase extends Dexie {
  outbox!: Table<OutboxOp, string>;

  constructor(name = "sms-offline-outbox") {
    super(name);
    this.version(1).stores({
      // opId is the primary key; status and createdAt are indexed since sync() and
      // getSyncSummary() both filter/sort on them.
      outbox: "opId, status, createdAt",
    });
  }
}

/**
 * Queues a write. `opId` must be generated by the caller (e.g. `crypto.randomUUID()`) --
 * it is the idempotency key the server keys off of, so it must survive retries unchanged.
 */
export async function enqueue(
  db: OutboxDatabase,
  op: { opId: string; entity: Entity; payload: Payload; createdAt?: string },
): Promise<void> {
  const now = op.createdAt ?? new Date().toISOString();
  await db.outbox.put({
    opId: op.opId,
    entity: op.entity,
    payload: op.payload,
    createdAt: now,
    attempts: 0,
    status: "pending",
    nextRetryAt: now,
  });
}

export interface SyncSummary {
  synced: number;
  pending: number; // includes "syncing"
  error: number;
}

/** Counts ops by status, for the visible Synced / Pending n / Error indicator. */
export async function getSyncSummary(db: OutboxDatabase): Promise<SyncSummary> {
  const all = await db.outbox.toArray();
  const summary: SyncSummary = { synced: 0, pending: 0, error: 0 };
  for (const op of all) {
    if (op.status === "synced") summary.synced += 1;
    else if (op.status === "error") summary.error += 1;
    else summary.pending += 1; // "pending" or "syncing"
  }
  return summary;
}

/** Resets an errored op so the next sync() call will try it again. */
export async function manualRetry(db: OutboxDatabase, opId: string): Promise<void> {
  const now = new Date().toISOString();
  await db.outbox.update(opId, { status: "pending", attempts: 0, nextRetryAt: now, lastError: undefined });
}

/**
 * Exponential backoff, capped at maxMs. Exported so it can be unit-tested and reasoned
 * about on its own, separately from the retry bookkeeping in sync().
 */
export function nextRetryDelayMs(attempts: number, baseMs = 500, maxMs = 30_000): number {
  const delay = baseMs * 2 ** attempts;
  return Math.min(delay, maxMs);
}

/** The network call is injected so this module never imports fetch/XHR directly, and unit
 * tests can exercise every branch (success, rejection, transient failure) without a server. */
export type ApplyOpsFn = (ops: readonly OutboxOp[]) => Promise<readonly ApplyOpResult[]>;

export interface SyncOptions {
  batchSize?: number;
  maxAttempts?: number;
  backoffBaseMs?: number;
  backoffMaxMs?: number;
  /** Injectable clock, for deterministic backoff tests. Defaults to `Date.now`. */
  now?: () => number;
}

/**
 * Sends every eligible pending op to the server, in batches, and updates each op's status
 * from the response. Eligible means status "pending" AND nextRetryAt has passed -- an op
 * that failed transiently and is backing off is simply skipped until its turn comes back
 * around on a later sync() call (see nextRetryDelayMs). This function makes one pass and
 * returns; it does not loop or sleep internally, matching how a phone app actually gets a
 * chance to sync -- on app open, on the browser's `online` event, and on a foreground
 * timer, none of which need this function to block.
 */
export async function sync(db: OutboxDatabase, applyOps: ApplyOpsFn, options: SyncOptions = {}): Promise<void> {
  const batchSize = options.batchSize ?? 50;
  const maxAttempts = options.maxAttempts ?? 5;
  const backoffBaseMs = options.backoffBaseMs ?? 500;
  const backoffMaxMs = options.backoffMaxMs ?? 30_000;
  const now = options.now ?? Date.now;
  const nowMs = now();

  // An op can be left in "syncing" if the app was closed or reloaded mid-request -- there is
  // no event that fires when that happens, so the only way to notice is here, the next time
  // anything calls sync(). We can't know whether that interrupted request reached the server,
  // but retrying is safe regardless: apply_ops() is idempotent by op_id, so at worst this is a
  // harmless duplicate delivery (see docs/research/offline-spike.md). Unlike a genuine network
  // failure, the interruption says nothing about server/network health, so recovery does not
  // apply backoff -- it makes the op immediately eligible again in this same sync() call.
  const stuck = await db.outbox.where("status").equals("syncing").toArray();
  if (stuck.length > 0) {
    await db.transaction("rw", db.outbox, async () => {
      for (const op of stuck) {
        const attempts = op.attempts + 1;
        const status: OutboxStatus = attempts >= maxAttempts ? "error" : "pending";
        await db.outbox.update(op.opId, {
          attempts,
          status,
          nextRetryAt: new Date(nowMs).toISOString(),
          lastError: status === "error" ? "interrupted" : undefined,
        });
      }
    });
  }

  const eligible = (await db.outbox.where("status").equals("pending").toArray())
    .filter((op) => new Date(op.nextRetryAt).getTime() <= nowMs)
    .sort((a, b) => a.createdAt.localeCompare(b.createdAt));

  for (let i = 0; i < eligible.length; i += batchSize) {
    const batch = eligible.slice(i, i + batchSize);
    await db.outbox.where("opId").anyOf(batch.map((op) => op.opId)).modify({ status: "syncing" });

    let results: readonly ApplyOpResult[];
    try {
      results = await applyOps(batch);
    } catch (networkError) {
      await db.transaction("rw", db.outbox, async () => {
        for (const op of batch) {
          await bumpAttempt(db, op, maxAttempts, backoffBaseMs, backoffMaxMs, now(), describeError(networkError));
        }
      });
      continue; // this batch failed transiently; still attempt any remaining batches
    }

    const byId = new Map(results.map((r) => [r.opId, r]));
    await db.transaction("rw", db.outbox, async () => {
      for (const op of batch) {
        const result = byId.get(op.opId);
        if (!result) {
          await bumpAttempt(db, op, maxAttempts, backoffBaseMs, backoffMaxMs, now(), "no_result_from_server");
        } else if (result.status === "applied") {
          await db.outbox.update(op.opId, { status: "synced", lastError: undefined });
        } else {
          // A typed rejection (locked/finalised/unknown) is terminal: retrying will not
          // change the outcome, so this goes straight to "error", not back to "pending".
          await db.outbox.update(op.opId, { status: "error", lastError: result.reason ?? "rejected" });
        }
      }
    });
  }
}

async function bumpAttempt(
  db: OutboxDatabase,
  op: OutboxOp,
  maxAttempts: number,
  baseMs: number,
  maxMs: number,
  nowMs: number,
  errorMessage: string,
): Promise<void> {
  const attempts = op.attempts + 1;
  const status: OutboxStatus = attempts >= maxAttempts ? "error" : "pending";
  await db.outbox.update(op.opId, {
    attempts,
    status,
    nextRetryAt: new Date(nowMs + nextRetryDelayMs(attempts, baseMs, maxMs)).toISOString(),
    lastError: errorMessage,
  });
}

function describeError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
